[config]
schemaVersion = "1.0.0"

[general]
repository = "https://thunderstore.io"

[package]
namespace = "JackEhttack"
name = "DiminishingReturns"
description = "Adds Diminishing Returns to repeated visits to the same planet."
websiteUrl = "https://github.com/JackEhttack/DiminishingReturns"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack = "5.4.2100"
Evaisa-HookGenPatcher = "0.0.5"

[build]
icon = "icon.png"
readme = "README.md"
outdir = "build"

[[build.copy]]
source = "DiminishingReturns/bin/DiminishingReturns.dll"
target = "BepInEx/plugins/DiminishingReturns.dll"

[[build.copy]]
source = "CHANGELOG.md"
target = "CHANGELOG.md"

[[build.copy]]
source = "LICENSE"
target = "LICENSE"

[publish]
communities = ["lethal-company"]

[publish.categories]
# The categories are available at https://thunderstore.io near of the search bar
lethal-company = ["bepinex", "mods", "server-side", "tweaks & quality of life"]
